Image upload UI
maxi-booking/d8base-frontend pull request #195
Opened 2021-03-31 15:01 UTC by enkryptor

2021-03-31 21:09 UTC, vitslepukhin requested changes

2021-03-31 21:09 UTC, vitslepukhin commented on src/app/master/components/master-profile-services/master-profile-services.component.html
>  <ng-container *ngIf="context$ | async as context">
Need to prettier the template.
Wouldn't be better to place add-new-service-card to top of list?

2021-04-03 08:27 UTC, vitslepukhin requested changes

2021-04-05 07:20 UTC, vitslepukhin requested changes

2021-04-05 07:44 UTC, enkryptor commented on src/app/shared/components/service-photos/service-photos.component.html
> +  <ion-list class="photo-slider" *appIfSpinner="servicePhotos.length > 0">
I have no idea how that happened. The latter  has to be *ngIf.

2021-04-05 11:29 UTC, vitslepukhin approved these changes

2021-04-05 11:47 UTC, merged