feat: iterating url method
maxi-booking/d8base-frontend pull request #463
Opened 2022-01-25 17:08 UTC by alexeyburov80

Перенес url во внешний json.

2022-02-01 21:33 UTC, ennaque requested changes

2022-02-01 21:33 UTC, ennaque commented on src/app/core/services/location/abstract-ip-service.ts
> +
must throw an error from here because in this case onErrorResumeNext wont start next request, null will be returned

2022-02-01 21:33 UTC, ennaque commented on src/app/core/services/location/abstract-ip-service.ts
> +            catchError(() => of(null)),
same

2022-02-01 21:33 UTC, ennaque commented on src/app/core/services/location/guess-location-by-ip.services.ts
> +        return { city: data.city, countryCode: data.country_code };
data should be checked, can be undefined or empty string
provide error into sentry service if there is an access error or if response format has changed
same for other services

2022-02-01 21:33 UTC, ennaque commented on src/environments/keys.ts
> +{
auth keys should be removed from public repo, store it in env.ts prob

2022-02-02 04:33 UTC, alexeyburov80 commented on src/app/core/services/location/abstract-ip-service.ts
> +
replaced by throw

2022-02-02 04:34 UTC, alexeyburov80 commented on src/app/core/services/location/abstract-ip-service.ts
> +            catchError(() => of(null)),
removed

2022-02-02 04:35 UTC, alexeyburov80 commented on src/app/core/services/location/guess-location-by-ip.services.ts
> +        return { city: data.city, countryCode: data.country_code };
add check

2022-02-02 04:35 UTC, alexeyburov80 commented on src/environments/keys.ts
> +{
removed

2022-02-02 12:03 UTC, ennaque approved these changes

2022-02-02 18:28 UTC, merged