Add search API
maxi-booking/d8base-frontend pull request #49
Opened 2020-12-09 11:19 UTC by vitslepukhin

2020-12-09 12:10 UTC, enkryptor commented on src/app/ng-swagger-gen.json
> +  "apiModule": true,
maybe should keep it `false`

2020-12-09 12:55 UTC, ennaque requested changes
need to fix code style

2020-12-09 13:05 UTC, enkryptor approved these changes

2020-12-09 21:38 UTC, ennaque approved these changes

2020-12-10 09:02 UTC, enkryptor commented on src/app/search/search-page.component.scss
> +  display: block;
let's move this to the `:host`: block in the component scss

2020-12-10 09:21 UTC, enkryptor commented on src/app/search/components/search-result/search-result.component.ts
> +import {Search, ServiceList} from '../../../api/models';
let's use absolute path here

2020-12-11 06:20 UTC, merged