Feature/slepukhin/wizard order
maxi-booking/d8base-frontend pull request #56
Opened 2020-12-14 08:30 UTC by vitslepukhin

2020-12-14 10:04 UTC, enkryptor commented on src/app/core/services/location/professional-location.service.ts
> +export type FullLocation = {
separate file?

2020-12-14 10:16 UTC, enkryptor commented on src/app/order/order-steps.ts
> +    isComplete: boolean;
`isValid` ?

2020-12-14 10:38 UTC, webmalc approved these changes

2020-12-14 10:59 UTC, enkryptor commented on src/app/order/components/step-container/step-container.component.ts
> +            .pipe(take(1), takeUntil(this.ngDestroy$))
let's emit state change on "next" button pressed

2020-12-14 11:13 UTC, enkryptor commented on src/app/order/order-steps.ts
> +    ids: [
`order`?

2020-12-14 11:45 UTC, enkryptor requested changes
update step state only when "Next" button is pressed

2020-12-14 11:45 UTC, enkryptor commented on src/app/core/services/location/professional-location.service.ts
> +import {ProfessionalLocationInline} from '../../../api/models';
please use absolute paths

2020-12-14 11:46 UTC, enkryptor commented on src/app/order/abstract/step.ts
> +export abstract class StepComponent<T extends any> implements OnDestroy {
just `T` is enough

2020-12-14 14:04 UTC, ennaque approved these changes

2020-12-15 14:35 UTC, enkryptor approved these changes

2020-12-15 17:23 UTC, merged